"""
===============================================================================
Project: LegacyLift
File: pdf_export.py

Author: Samuel Raymond Kwibe
Education: B.S. Computer Science Student, Southern New Hampshire University (SNHU)

Professional Focus:
- Software Engineering
- Artificial Intelligence (AI)
- Cloud Engineering
- Full-Stack Development

LinkedIn:
https://www.linkedin.com/in/samuel-kwibe-371633249/

GitHub:
https://github.com/Samkwibe

Description:
Converts markdown reports into professional PDF documents using fpdf2.

Copyright © 2026 Samuel Raymond Kwibe.
All Rights Reserved.
===============================================================================
"""
from fpdf import FPDF

class ReportPDF(FPDF):
    def header(self):
        # Logo or Title
        self.set_font("helvetica", "B", 15)
        self.cell(0, 10, "LegacyLift Analysis Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "I", 10)
        self.cell(0, 10, "Generated by Samuel Raymond Kwibe's AI Mentorship Engine", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

def markdown_to_pdf(markdown_text):
    """
    Converts a simple markdown string to a PDF byte stream.
    Strips basic markdown syntax for a clean PDF.
    """
    pdf = ReportPDF()
    pdf.add_page()
    pdf.set_font("helvetica", size=11)
    
    # Very basic markdown parsing
    for line in markdown_text.split('\n'):
        if line.startswith('# '):
            pdf.set_font("helvetica", "B", 16)
            line = line[2:]
        elif line.startswith('## '):
            pdf.set_font("helvetica", "B", 14)
            line = line[3:]
        elif line.startswith('### '):
            pdf.set_font("helvetica", "B", 12)
            line = line[4:]
        elif line.startswith('**') and line.endswith('**'):
            pdf.set_font("helvetica", "B", 11)
            line = line[2:-2]
        else:
            pdf.set_font("helvetica", size=11)
            
        # Clean up other basic markdown elements
        line = line.replace('**', '')
        line = line.replace('`', '')
        
        # Write line
        # Use multi_cell for wrapping
        pdf.multi_cell(0, 6, text=line)
        
    return bytes(pdf.output())
